"""empty message

Revision ID: 991e202f8ee5
Revises: 
Create Date: 2019-05-26 14:46:20.443455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '991e202f8ee5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('UID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UserName', sa.Text(), nullable=False),
    sa.Column('SID', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('UID')
    )
    op.create_table('Score',
    sa.Column('SCID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UID', sa.Integer(), nullable=True),
    sa.Column('Score1', sa.Integer(), nullable=False),
    sa.Column('Score2', sa.Integer(), nullable=False),
    sa.Column('Score3', sa.Integer(), nullable=False),
    sa.Column('Score4', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['UID'], ['User.UID'], ),
    sa.PrimaryKeyConstraint('SCID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Score')
    op.drop_table('User')
    # ### end Alembic commands ###
